services:
  robison_website:
    build:
      context: .
      dockerfile: ./tests/integration/server/server.Dockerfile
    init: true
    ports:
      - 5000:5000
    command:
      - /workarea/server.sh

  client:
    build:
      context: .
      dockerfile: ./input/client.Dockerfile
    init: true
    command:
      - /workarea/client.sh
    volumes:
      - ./data:/data

  broadcast:
    build:
      context: .
      dockerfile: ./output/broadcast.Dockerfile
    init: true
    ports:
      - 5001:5001
    command:
      - /workarea/broadcast.sh
    volumes:
      - ./data:/data
  